// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY3vOGb_vkOFwtNfa0J2kJM3jA5sSCi_Y',
    appId: '1:238319939515:web:136a497e4358ebb64fde9e',
    messagingSenderId: '238319939515',
    projectId: 'techdunkers',
    authDomain: 'techdunkers.firebaseapp.com',
    storageBucket: 'techdunkers.appspot.com',
    measurementId: 'G-E5HNE0TCPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvGm_8Cgx_Meycu6-Qvc53k9ZLQberTNw',
    appId: '1:238319939515:android:fa0a0327bacc43254fde9e',
    messagingSenderId: '238319939515',
    projectId: 'techdunkers',
    storageBucket: 'techdunkers.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCftSl0pygNxANigjQpHEFZ8_HVlOJ9y7Y',
    appId: '1:238319939515:ios:0a33c6c57d87248d4fde9e',
    messagingSenderId: '238319939515',
    projectId: 'techdunkers',
    storageBucket: 'techdunkers.appspot.com',
    iosBundleId: 'com.example.techDunkers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCftSl0pygNxANigjQpHEFZ8_HVlOJ9y7Y',
    appId: '1:238319939515:ios:05dcab531babd7c84fde9e',
    messagingSenderId: '238319939515',
    projectId: 'techdunkers',
    storageBucket: 'techdunkers.appspot.com',
    iosBundleId: 'com.example.techDunkers.RunnerTests',
  );
}
